#server:
#  port: 30000
#
#spring:
#  application:
#    name: gulimall-third-party
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI4G6wiyWqtMJJhsQpNj3V
#      secret-key: jKcwKVqw0GxM6srxzCdC7Jj2ksqEIH
#      oss:
#        bucket: gulimall-gemini-hello
#        endpoint: oss-cn-beijing.aliyuncs.com